version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3000"
    networks:
      - twitter-network
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=twitter

  tweet-service:
    build: ./tweet-service
    ports:
      - "3002:3000"
    networks:
      - twitter-network
    environment:
      - MONGO_URL=mongodb://mongo:27017/tweetdb

  newsfeed-service:
    build: ./newsfeed-service
    ports:
      - "3003:3000"
    networks:
      - twitter-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitter
    ports:
      - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
    networks:
      - twitter-network

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - twitter-network
    volumes:
      - mongodata:/data/db

  kafka:
    image: bitnami/kafka:3.5.0
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LOG_DIRS=/opt/bitnami/kafka/data
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    volumes:
      - ./kafka-data:/opt/bitnami/kafka/data
    networks:
      - twitter-network

networks:
  twitter-network:
    driver: bridge

volumes:
  pgdata:
  mongodata:
  kafka-data:
